{
  "x-generator": "NSwag v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))",
  "openapi": "3.0.0",
  "info": {
    "title": "CommercialPolicyBenchmark API",
    "version": "v2.0"
  },
  "servers": [
    {
      "url": "https://api.zywave.com"
    }
  ],
  "paths": {
    "/commercialpolicybenchmark/v2.0/assessment/gettotallosscount": {
      "post": {
        "tags": [
          "Assessment"
        ],
        "summary": "GetTotalLossCount endpoint.",
        "operationId": "Assessment_GetTotalLossCount",
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LossAssessmentSearchRequest"
              },
              "example": {
                "ClientLimit": null,
                "MostRecentLossYear": null,
                "OldestLossYear": null,
                "Naics": null,
                "CoverageId": 0,
                "LineOfBusinessId": null,
                "ExposureType": null,
                "ExposureRangeLow": 0.0,
                "ExposureRangeHigh": 0.0,
                "OrganizationType": null
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "integer",
                  "format": "int32"
                }
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      }
    },
    "/commercialpolicybenchmark/v2.0/assessment/gettotalprogramcount": {
      "post": {
        "tags": [
          "Assessment"
        ],
        "summary": "GetTotalProgramCount endpoint.",
        "operationId": "Assessment_GetTotalProgramCount",
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProgramAssessmentSearchRequest"
              },
              "example": {
                "OldestTrailing": 0,
                "NewestTrailing": 0,
                "Premium": 0.0,
                "Limit": 0.0,
                "Retention": 0.0,
                "Naics": null,
                "CoverageId": 0,
                "LineOfBusinessId": null,
                "ExposureType": null,
                "ExposureRangeLow": 0.0,
                "ExposureRangeHigh": 0.0,
                "OrganizationType": null
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "integer",
                  "format": "int32"
                }
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      }
    },
    "/commercialpolicybenchmark/v2.0/assessment/getassessmentdata": {
      "post": {
        "tags": [
          "Assessment"
        ],
        "summary": "GetAssessmentData endpoint.",
        "operationId": "Assessment_GetAssessmentData",
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProgramAssessmentSearchRequest"
              },
              "example": {
                "OldestTrailing": 0,
                "NewestTrailing": 0,
                "Premium": 0.0,
                "Limit": 0.0,
                "Retention": 0.0,
                "Naics": null,
                "CoverageId": 0,
                "LineOfBusinessId": null,
                "ExposureType": null,
                "ExposureRangeLow": 0.0,
                "ExposureRangeHigh": 0.0,
                "OrganizationType": null
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AssessmentData"
                }
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      }
    },
    "/commercialpolicybenchmark/v2.0/assessment/getrpmdistributiondata": {
      "post": {
        "tags": [
          "Assessment"
        ],
        "summary": "GetRpmDistributionData endpoint.",
        "operationId": "Assessment_GetRpmDistributionData",
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProgramAssessmentSearchRequest"
              },
              "example": {
                "OldestTrailing": 0,
                "NewestTrailing": 0,
                "Premium": 0.0,
                "Limit": 0.0,
                "Retention": 0.0,
                "Naics": null,
                "CoverageId": 0,
                "LineOfBusinessId": null,
                "ExposureType": null,
                "ExposureRangeLow": 0.0,
                "ExposureRangeHigh": 0.0,
                "OrganizationType": null
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RpmData"
                }
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      }
    },
    "/commercialpolicybenchmark/v2.0/company/{id}": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "return company info.",
        "operationId": "Company_GetCompany",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Company"
                }
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      }
    },
    "/commercialpolicybenchmark/v2.0/company": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "return list of companies.",
        "operationId": "Company_SearchCompanies",
        "parameters": [
          {
            "name": "$filter",
            "x-originalName": "filter",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          },
          {
            "name": "$orderBy",
            "x-originalName": "orderBy",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 2
          },
          {
            "name": "$skip",
            "x-originalName": "skip",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 0
            },
            "x-position": 3
          },
          {
            "name": "$top",
            "x-originalName": "top",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 100
            },
            "x-position": 4
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PagedResultOfCompany"
                }
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      }
    },
    "/commercialpolicybenchmark/v2.0/referencedata/revenue": {
      "get": {
        "tags": [
          "ReferenceData"
        ],
        "summary": "return revenue ranges.",
        "operationId": "ReferenceData_GetRevenueRanges",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Range"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/commercialpolicybenchmark/v2.0/referencedata/marketcap": {
      "get": {
        "tags": [
          "ReferenceData"
        ],
        "summary": "return market cap ranges.",
        "operationId": "ReferenceData_GetMarketCapRanges",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Range"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/commercialpolicybenchmark/v2.0/referencedata/employeecount": {
      "get": {
        "tags": [
          "ReferenceData"
        ],
        "summary": "return employee ranges.",
        "operationId": "ReferenceData_GetEmployeeCountRanges",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Range"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/commercialpolicybenchmark/v2.0/referencedata/organizationtype": {
      "get": {
        "tags": [
          "ReferenceData"
        ],
        "summary": "return organization types.",
        "operationId": "ReferenceData_GetOrganizationTypes",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/OrganizationType"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/commercialpolicybenchmark/v2.0/referencedata/coveragelinesofbusiness": {
      "get": {
        "tags": [
          "ReferenceData"
        ],
        "summary": "return coverage(s)/lob(s).",
        "operationId": "ReferenceData_GetCoverageLineOfBusiness",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CoverageLineOfBusiness"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/commercialpolicybenchmark/v2.0/referencedata/naicscodes": {
      "get": {
        "tags": [
          "ReferenceData"
        ],
        "summary": "return naics codes.",
        "operationId": "ReferenceData_GetNAICSCodesNew",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/NAICSCode"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/commercialpolicybenchmark/v2.0/lossdetails/{lossEventId}": {
      "get": {
        "tags": [
          "LossDetails"
        ],
        "summary": "return loss details.",
        "operationId": "LossDetails_GetLossDetails",
        "parameters": [
          {
            "name": "lossEventId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LossEventDetails"
                }
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      }
    },
    "/commercialpolicybenchmark/v2.0/lossdetails/getlimitadequacydata": {
      "post": {
        "tags": [
          "LossDetails"
        ],
        "summary": "return limit adequacy chart data.",
        "operationId": "LossDetails_GetLimitAdequacy",
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LossAssessmentSearchRequest"
              },
              "example": {
                "ClientLimit": null,
                "MostRecentLossYear": null,
                "OldestLossYear": null,
                "Naics": null,
                "CoverageId": 0,
                "LineOfBusinessId": null,
                "ExposureType": null,
                "ExposureRangeLow": 0.0,
                "ExposureRangeHigh": 0.0,
                "OrganizationType": null
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LossEventData"
                }
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ProblemDetails": {
        "type": "object",
        "additionalProperties": {
          "nullable": true
        },
        "properties": {
          "type": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "detail": {
            "type": "string",
            "nullable": true
          },
          "instance": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "LossAssessmentSearchRequest": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AssessmentSearchRequest"
          },
          {
            "type": "object",
            "description": "LossAssessmentSearchRequest class.",
            "additionalProperties": false,
            "properties": {
              "clientLimit": {
                "type": "number",
                "description": "Default value is 0.\nClientLimit nullable property.",
                "format": "decimal",
                "default": 0,
                "nullable": true
              },
              "mostRecentLossYear": {
                "type": "integer",
                "description": "MostRecentLossYear nullable property.",
                "format": "int32",
                "nullable": true
              },
              "oldestLossYear": {
                "type": "integer",
                "description": "OldestLossYear nullable property.",
                "format": "int32",
                "nullable": true
              }
            }
          }
        ]
      },
      "AssessmentSearchRequest": {
        "type": "object",
        "description": "AssessmentSearchRequest class.",
        "additionalProperties": false,
        "properties": {
          "naics": {
            "type": "array",
            "description": "BindRequired.\nNaics property.",
            "nullable": true,
            "items": {
              "type": "string"
            }
          },
          "coverageId": {
            "type": "integer",
            "description": "BindRequired.\nCoverageId property.",
            "format": "int32"
          },
          "lineOfBusinessId": {
            "type": "array",
            "description": "BindRequired.\nLineOfBusinessId property.",
            "nullable": true,
            "items": {
              "type": "integer",
              "format": "int32"
            }
          },
          "exposureType": {
            "type": "string",
            "description": "BindRequired.\nDefault value is \"Revenues\".\nExposureType property.",
            "default": "Revenues",
            "nullable": true
          },
          "exposureRangeLow": {
            "type": "number",
            "description": "BindRequired.\nExposureRangeLow property.",
            "format": "decimal"
          },
          "exposureRangeHigh": {
            "type": "number",
            "description": "BindRequired.\nExposureRangeHigh property.",
            "format": "decimal"
          },
          "organizationType": {
            "type": "array",
            "description": "OrganizationType property.",
            "default": "All",
            "nullable": true,
            "items": {
              "type": "string"
            }
          }
        }
      },
      "ProgramAssessmentSearchRequest": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AssessmentSearchRequest"
          },
          {
            "type": "object",
            "description": "ProgramAssessmentSearchRequest class.",
            "additionalProperties": false,
            "properties": {
              "oldestTrailing": {
                "type": "integer",
                "description": "Default value is 24.\nOldestTrailing property.",
                "format": "int32",
                "default": 24
              },
              "newestTrailing": {
                "type": "integer",
                "description": "Default value is 0.\nNewestTrailing property.",
                "format": "int32",
                "default": 0
              },
              "premium": {
                "type": "number",
                "description": "Default value is 0.\nPremium property.",
                "format": "decimal",
                "default": 0
              },
              "limit": {
                "type": "number",
                "description": "Default value is 0.\nLimit property.",
                "format": "decimal",
                "default": 0
              },
              "retention": {
                "type": "number",
                "description": "Default value is 0.\nRetention property.",
                "format": "decimal",
                "default": 0
              }
            }
          }
        ]
      },
      "AssessmentData": {
        "type": "object",
        "description": "AssessmentData class.",
        "additionalProperties": false,
        "properties": {
          "limitDistribution": {
            "description": "LimitDistribution property.",
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/DistributionData"
              }
            ]
          },
          "premiumDistribution": {
            "description": "PremiumDistribution property.",
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/DistributionData"
              }
            ]
          },
          "retentionDistribution": {
            "description": "RetentionDistribution property.",
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/DistributionData"
              }
            ]
          }
        }
      },
      "DistributionData": {
        "type": "object",
        "description": "DistributionData class.",
        "additionalProperties": false,
        "properties": {
          "chartDescription": {
            "type": "string",
            "description": "ChartDescription property.",
            "nullable": true
          },
          "bands": {
            "type": "array",
            "description": "Bands property.",
            "nullable": true,
            "items": {
              "$ref": "#/components/schemas/Bands"
            }
          }
        }
      },
      "Bands": {
        "type": "object",
        "description": "Bands class.",
        "additionalProperties": false,
        "properties": {
          "bandSeq": {
            "type": "integer",
            "description": "BandSeq property.",
            "format": "int32"
          },
          "bandDescription": {
            "type": "string",
            "description": "BandDescription property.",
            "nullable": true
          },
          "programCount": {
            "type": "integer",
            "description": "ProgramCount property.",
            "format": "int32"
          }
        }
      },
      "RpmData": {
        "type": "object",
        "description": "RpmData class.",
        "additionalProperties": false,
        "properties": {
          "firstQuartile": {
            "type": "number",
            "description": "firstQuartile property.",
            "format": "float"
          },
          "median": {
            "type": "number",
            "description": "median property.",
            "format": "float"
          },
          "fourthQuartile": {
            "type": "number",
            "description": "fourthQuartile property.",
            "format": "float"
          },
          "maxRpm": {
            "type": "number",
            "description": "maxRpm property.",
            "format": "float"
          },
          "clientBar": {
            "type": "number",
            "description": "clientBar property.",
            "format": "float"
          },
          "nthPercent": {
            "type": "number",
            "description": "nthPercent property.",
            "format": "float"
          },
          "chartDescription": {
            "type": "string",
            "description": "chartDescription nullable property.",
            "nullable": true
          }
        }
      },
      "Company": {
        "type": "object",
        "description": "Company class.",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "integer",
            "description": "id property.",
            "format": "int32"
          },
          "companyName": {
            "type": "string",
            "description": "CompanyName property.",
            "nullable": true
          },
          "organizationType": {
            "type": "string",
            "description": "OrganizationType property.",
            "nullable": true
          },
          "naicsCode": {
            "type": "string",
            "description": "NaicsCode property",
            "nullable": true
          },
          "naics2": {
            "type": "integer",
            "description": "Naics2 property.",
            "format": "int32"
          },
          "naics3": {
            "type": "integer",
            "description": "Naics3 property.",
            "format": "int32"
          },
          "revenues": {
            "type": "number",
            "description": "Revenues property.",
            "format": "decimal"
          },
          "numberOfEmployees": {
            "type": "integer",
            "description": "NumberOfEmployees property.",
            "format": "int32"
          },
          "marketCap": {
            "type": "number",
            "description": "MarketCap property.",
            "format": "decimal"
          }
        }
      },
      "PagedResultOfCompany": {
        "type": "object",
        "description": "A model containing a collection of Content pieces and metadata about their position in a larger result list.",
        "additionalProperties": false,
        "properties": {
          "hasMoreResults": {
            "type": "boolean",
            "description": "A value indicating whether the larger result set has more results.",
            "nullable": true
          },
          "pageIndex": {
            "type": "integer",
            "description": "The index of the page reflected by the collection.",
            "format": "int32",
            "nullable": true
          },
          "pageSize": {
            "type": "integer",
            "description": "The size of the page relfected by the collection.",
            "format": "int32",
            "nullable": true
          },
          "skip": {
            "type": "integer",
            "description": "A value indicating how many of the previous values in the larger result set were omitted.",
            "format": "int32",
            "nullable": true
          },
          "take": {
            "type": "integer",
            "description": "The number of records retrieved from larger result set.",
            "format": "int32",
            "nullable": true
          },
          "totalCount": {
            "type": "integer",
            "description": "The total number of records in the larger result set.",
            "format": "int32",
            "nullable": true
          },
          "items": {
            "type": "array",
            "description": "The records retrieved from the larger result set.",
            "nullable": true,
            "items": {
              "$ref": "#/components/schemas/Company"
            }
          }
        }
      },
      "Range": {
        "type": "object",
        "description": "Range class.",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "integer",
            "description": "Id property.",
            "format": "int32"
          },
          "name": {
            "type": "string",
            "description": "Name property.",
            "nullable": true
          },
          "lowRange": {
            "type": "integer",
            "description": "LowRange property.",
            "format": "int64",
            "nullable": true
          },
          "highRange": {
            "type": "integer",
            "description": "HighRange property.",
            "format": "int64",
            "nullable": true
          }
        }
      },
      "OrganizationType": {
        "type": "object",
        "description": "OrganizationType class.",
        "additionalProperties": false,
        "properties": {
          "typeId": {
            "type": "string",
            "description": "TypeId property.",
            "nullable": true
          },
          "name": {
            "type": "string",
            "description": "Name property.",
            "nullable": true
          }
        }
      },
      "CoverageLineOfBusiness": {
        "type": "object",
        "description": "CoverageLineOfBusiness class.",
        "additionalProperties": false,
        "properties": {
          "coverageId": {
            "type": "integer",
            "description": "CoverageId property.",
            "format": "int32"
          },
          "coverageName": {
            "type": "string",
            "description": "CoverageName property.",
            "nullable": true
          },
          "lineOfBusinessId": {
            "type": "integer",
            "description": "LineOfBusinessId property.",
            "format": "int32"
          },
          "lineOfBusinessName": {
            "type": "string",
            "description": "LineOfBusinessName property.",
            "nullable": true
          }
        }
      },
      "NAICSCode": {
        "type": "object",
        "description": "NAICSCode class.",
        "additionalProperties": false,
        "properties": {
          "code": {
            "type": "string",
            "description": "Code property.",
            "nullable": true
          },
          "name": {
            "type": "string",
            "description": "Name property.",
            "nullable": true
          }
        }
      },
      "LossEventDetails": {
        "type": "object",
        "description": "LossEventDetails class.",
        "additionalProperties": false,
        "properties": {
          "lossName": {
            "type": "string",
            "description": "LossName property.",
            "nullable": true
          },
          "lossCategory": {
            "type": "string",
            "description": "LossCategory property.",
            "nullable": true
          },
          "lossType": {
            "type": "string",
            "description": "LossType property.",
            "nullable": true
          },
          "lossCoverage": {
            "type": "string",
            "description": "LossCoverage property.",
            "nullable": true
          },
          "lossLOB": {
            "type": "string",
            "description": "LossLOB property.",
            "nullable": true
          },
          "accidentDate": {
            "type": "string",
            "description": "AccidentDate property.",
            "format": "date-time",
            "nullable": true
          },
          "filingDate": {
            "type": "string",
            "description": "FilingDate property.",
            "format": "date-time",
            "nullable": true
          },
          "status": {
            "type": "string",
            "description": "Status property.",
            "nullable": true
          },
          "totalAmount": {
            "type": "number",
            "description": "TotalAmount property.",
            "format": "decimal",
            "nullable": true
          },
          "lossDetailsDescription": {
            "type": "string",
            "description": "LossDetailsDescription property.",
            "nullable": true
          }
        }
      },
      "LossEventData": {
        "type": "object",
        "description": "LossEventData class.",
        "additionalProperties": false,
        "properties": {
          "clientLimit": {
            "type": "number",
            "description": "ClientLimit property.",
            "format": "decimal",
            "nullable": true
          },
          "medianLimit": {
            "type": "integer",
            "description": "MedianLimit property.",
            "format": "int32",
            "nullable": true
          },
          "percentCovered": {
            "type": "integer",
            "description": "PercentCovered property.",
            "format": "int32"
          },
          "maxLoss": {
            "type": "number",
            "description": "MaxLoss property.",
            "format": "decimal"
          },
          "averageLoss": {
            "type": "integer",
            "description": "AverageLoss property.",
            "format": "int32"
          },
          "listOfCases": {
            "type": "array",
            "description": "ListOfCases property.",
            "nullable": true,
            "items": {
              "$ref": "#/components/schemas/ListOfCases"
            }
          }
        }
      },
      "ListOfCases": {
        "type": "object",
        "description": "ListOfCases class.",
        "additionalProperties": false,
        "properties": {
          "lossEventID": {
            "type": "integer",
            "description": "LossEventID property.",
            "format": "int32"
          },
          "lossAmount": {
            "type": "number",
            "description": "LossAmount property.",
            "format": "decimal",
            "nullable": true
          }
        }
      }
    },
    "securitySchemes": {
      "oidc": {
        "type": "oauth2",
        "openIdConnectUrl": "https://auth.zywave.com/.well-known/openid-configuration",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://auth.zywave.com/connect/authorize",
            "tokenUrl": "https://auth.zywave.com/connect/token",
            "scopes": {
              "api.commercialpolicybenchmark": "Full access to all api operations",
              "api.commercialpolicybenchmark:read": "Read-only access to api"
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "oidc": [
        "api.commercialpolicybenchmark",
        "api.commercialpolicybenchmark:read"
      ]
    }
  ]
}